#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

DREAMER_TASKS=${DREAMER_TASKS:-"h1touch-walk-v0 h1touch-door-v0"}
PPO_TASKS=${PPO_TASKS:-"$DREAMER_TASKS"}
SEEDS=${SEEDS:-"0"}
TRAIN_STEPS=${TRAIN_STEPS:-2000}
PPO_TRAIN_STEPS=${PPO_TRAIN_STEPS:-1000}
EVAL_STEPS=${EVAL_STEPS:-200}
PPO_EVAL_EPISODES=${PPO_EVAL_EPISODES:-1}
NUM_ENVS=${NUM_ENVS:-1}
NOISES=${NOISES:-"0.0 0.02"}
DROPS=${DROPS:-"0.0 0.2"}
MASS_SCALES=${MASS_SCALES:-"1.0 1.1"}
FRICTION_SCALES=${FRICTION_SCALES:-"1.0 0.8"}
RUN_PPO=${RUN_PPO:-1}
RUN_DYNAMICS=${RUN_DYNAMICS:-0}
RUNS_DIR=${RUNS_DIR:-outputs/runs_debug}
RESULTS_CSV=${RESULTS_CSV:-outputs/results/results_debug.csv}
ANALYSIS_CSV=${ANALYSIS_CSV:-outputs/results/contact_analysis_debug.csv}
FIGS_DIR=${FIGS_DIR:-outputs/figs_debug}
TACTILE_ERROR_CSV=${TACTILE_ERROR_CSV:-outputs/results/tactile_error_vs_success_debug.csv}
TACTILE_ERROR_FIG=${TACTILE_ERROR_FIG:-outputs/figs_debug/tactile_error_vs_success.png}
DYNAMICS_CSV=${DYNAMICS_CSV:-outputs/results/dynamics_summary_debug.csv}
DRY_RUN=${DRY_RUN:-0}

echo "Smoke test configuration"
echo "DREAMER_TASKS=$DREAMER_TASKS"
echo "PPO_TASKS=$PPO_TASKS"
echo "SEEDS=$SEEDS"
echo "TRAIN_STEPS=$TRAIN_STEPS"
echo "PPO_TRAIN_STEPS=$PPO_TRAIN_STEPS"
echo "EVAL_STEPS=$EVAL_STEPS"
echo "PPO_EVAL_EPISODES=$PPO_EVAL_EPISODES"
echo "NUM_ENVS=$NUM_ENVS"
echo "NOISES=$NOISES"
echo "DROPS=$DROPS"
echo "MASS_SCALES=$MASS_SCALES"
echo "FRICTION_SCALES=$FRICTION_SCALES"
echo "RUN_PPO=$RUN_PPO"
echo "RUN_DYNAMICS=$RUN_DYNAMICS"
echo "Target budget: a short smoke test on a single GPU, shorter in DRY_RUN=1"

DREAMER_TASKS="$DREAMER_TASKS" \
PPO_TASKS="$PPO_TASKS" \
SEEDS="$SEEDS" \
TRAIN_STEPS="$TRAIN_STEPS" \
PPO_TRAIN_STEPS="$PPO_TRAIN_STEPS" \
EVAL_STEPS="$EVAL_STEPS" \
PPO_EVAL_EPISODES="$PPO_EVAL_EPISODES" \
NUM_ENVS="$NUM_ENVS" \
NOISES="$NOISES" \
DROPS="$DROPS" \
MASS_SCALES="$MASS_SCALES" \
FRICTION_SCALES="$FRICTION_SCALES" \
RUN_PPO="$RUN_PPO" \
RUN_DYNAMICS="$RUN_DYNAMICS" \
RUNS_DIR="$RUNS_DIR" \
RESULTS_CSV="$RESULTS_CSV" \
ANALYSIS_CSV="$ANALYSIS_CSV" \
FIGS_DIR="$FIGS_DIR" \
TACTILE_ERROR_CSV="$TACTILE_ERROR_CSV" \
TACTILE_ERROR_FIG="$TACTILE_ERROR_FIG" \
DYNAMICS_CSV="$DYNAMICS_CSV" \
DRY_RUN="$DRY_RUN" \
bash ./run_all.sh
