#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

DREAMER_TASKS=${DREAMER_TASKS:-"h1touch-door-v0"}
DREAMER_VARIANTS=${DREAMER_VARIANTS:-"frontier_rgb_bct_spatial"}
SEEDS=${SEEDS:-"0"}
TRAIN_STEPS=${TRAIN_STEPS:-5000}
EVAL_STEPS=${EVAL_STEPS:-500}
NUM_ENVS=${NUM_ENVS:-1}
NOISES=${NOISES:-"0.0"}
DROPS=${DROPS:-"0.0"}
RUN_PPO=${RUN_PPO:-0}
RUN_DYNAMICS=${RUN_DYNAMICS:-0}
RUNS_DIR=${RUNS_DIR:-outputs/runs_rgb_smoke}
RESULTS_CSV=${RESULTS_CSV:-outputs/results/results_rgb_smoke.csv}

DREAMER_TASKS="$DREAMER_TASKS" \
DREAMER_VARIANTS="$DREAMER_VARIANTS" \
SEEDS="$SEEDS" \
TRAIN_STEPS="$TRAIN_STEPS" \
EVAL_STEPS="$EVAL_STEPS" \
NUM_ENVS="$NUM_ENVS" \
NOISES="$NOISES" \
DROPS="$DROPS" \
RUN_PPO="$RUN_PPO" \
RUN_DYNAMICS="$RUN_DYNAMICS" \
RUNS_DIR="$RUNS_DIR" \
RESULTS_CSV="$RESULTS_CSV" \
bash ./run_all.sh
